// Code generated by "stringer -type=UnderlyingType -linecomment -trimprefix=UnderlyingType -output underlying-type-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnderlyingTypeUndefined-0]
	_ = x[UnderlyingTypeStaticCobra-1]
	_ = x[UnderlyingTypeDynamicCobra-2]
	_ = x[UnderlyingTypeStaticGeneral-3]
	_ = x[UnderlyingTypeDynamicGeneral-4]
	_ = x[UnderlyingTypeStaticError-5]
	_ = x[UnderlyingTypeSentinelError-6]
	_ = x[UnderlyingTypeStaticErrorWrapper-7]
	_ = x[UnderlyingTypeDynamicError-8]
	_ = x[UnderlyingTypeDynamicErrorWrapper-9]
}

const _UnderlyingType_name = "UndefinedStaticCobraDynamicCobraStaticGeneralDynamicGeneralStaticErrorSentinelErrorStaticErrorWrapperDynamicErrorDynamicErrorWrapper"

var _UnderlyingType_index = [...]uint8{0, 9, 20, 32, 45, 59, 70, 83, 101, 113, 132}

func (i UnderlyingType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UnderlyingType_index)-1 {
		return "UnderlyingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnderlyingType_name[_UnderlyingType_index[idx]:_UnderlyingType_index[idx+1]]
}
