// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 📨 Internationalisation
//
// A test message for internationalisation.
// =============================================================================

// InternationalisationTemplData Internationalisation.
type InternationalisationTemplData struct {
	Li18ngoTemplData
}

// Message returns the i18n message for InternationalisationTemplData.
func (td InternationalisationTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "internationalisation.test",
		Description: "Internationalisation",
		Other:       "internationalisation",
	}
}

// =============================================================================
// 📨 Localisation
//
// A test message for localisation.
// =============================================================================

// LocalisationTemplData Localisation.
type LocalisationTemplData struct {
	Li18ngoTemplData
}

// Message returns the i18n message for LocalisationTemplData.
func (td LocalisationTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "localisation.test",
		Description: "Localisation",
		Other:       "localisation",
	}
}

// =============================================================================
// 📨 PavementGraffitiReportGrafficoTest
//
// A test message for pavement graffiti reporting.
// =============================================================================

// PavementGraffitiReportGrafficoTestTemplData Report of graffiti found on a
// pavement.
type PavementGraffitiReportGrafficoTestTemplData struct {
	Li18ngoTemplData
	// Primary is the primary colour of the graffiti
	Primary string
}

// Message returns the i18n message for
// PavementGraffitiReportGrafficoTestTemplData.
func (td PavementGraffitiReportGrafficoTestTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "pavement-graffiti-report.graffico.test",
		Description: "Report of graffiti found on a pavement",
		Other:       "Found graffiti on pavement; primary colour: '{{.Primary}}'",
	}
}

// NewPavementGraffitiReportGrafficoTestTemplData creates a new
// PavementGraffitiReportGrafficoTestTemplData.
func NewPavementGraffitiReportGrafficoTestTemplData(primary string) PavementGraffitiReportGrafficoTestTemplData {
	return PavementGraffitiReportGrafficoTestTemplData{
		Li18ngoTemplData: Li18ngoTemplData{},
		Primary:          primary,
	}
}

// =============================================================================
// 📨 UsingConfigFile
//
// UsingConfigFile is printed on startup to indicate which configuration file
// has been loaded.
// =============================================================================

// UsingConfigFileTemplData Message to indicate which config is being used.
type UsingConfigFileTemplData struct {
	Li18ngoTemplData
	// ConfigFileName is the name of the config file being used
	ConfigFileName string
}

// Message returns the i18n message for UsingConfigFileTemplData.
func (td UsingConfigFileTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "using-config-file",
		Description: "Message to indicate which config is being used",
		Other:       "Using config file: '{{.ConfigFileName}}'",
	}
}

// NewUsingConfigFileTemplData creates a new UsingConfigFileTemplData.
func NewUsingConfigFileTemplData(configFileName string) UsingConfigFileTemplData {
	return UsingConfigFileTemplData{
		Li18ngoTemplData: Li18ngoTemplData{},
		ConfigFileName:   configFileName,
	}
}

// =============================================================================
// 📨 WrongSourceIDGrafficoTest
//
// This message has the wrong source ID and should be ignored by i18n-gen.
// =============================================================================

// WrongSourceIDGrafficoTestTemplData Message with wrong source ID for testing
// purposes.
type WrongSourceIDGrafficoTestTemplData struct {
	Li18ngoTemplData
}

// Message returns the i18n message for WrongSourceIDGrafficoTestTemplData.
func (td WrongSourceIDGrafficoTestTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "wrong-source-id.graffico.test",
		Description: "Message with wrong source ID for testing purposes",
		Other:       "This message should be ignored by i18n-gen.",
	}
}
