// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ NotADirectory
//
// NotADirectoryError is used when a file system path is expected to be a
// directory but is not.
// =============================================================================

// NotADirectoryTemplData File system path is not a directory.
type NotADirectoryTemplData struct {
	Li18ngoTemplData
	// Path is the file system path that was expected to be a directory but is not (e.g. '/etc/config.yaml')
	Path string
}

// Message creates a new i18n message using the template data.
func (td NotADirectoryTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "not-a-directory.dynamic-error",
		Description: "File system path is not a directory",
		Other:       "file system path '{{.Path}}', is not a directory",
	}
}

// NotADirectoryError File system path is not a directory.
type NotADirectoryError struct {
	li18ngo.LocalisableError
	NotADirectoryTemplData
}

// NewNotADirectoryError creates a new NotADirectoryError.
func NewNotADirectoryError(path string) error {
	td := NotADirectoryTemplData{
		Li18ngoTemplData: Li18ngoTemplData{},
		Path:             path,
	}
	return &NotADirectoryError{
		LocalisableError:       li18ngo.LocalisableError{Data: td},
		NotADirectoryTemplData: td,
	}
}

// =============================================================================
// ❌ PathNotFound
//
// PathNotFoundError is used when a directory or file path does not exist.
// =============================================================================

// PathNotFoundTemplData Directory or file path does not exist.
type PathNotFoundTemplData struct {
	Li18ngoTemplData
	// Name is the name of the path that was not found (e.g. 'Config')
	Name string
	// Path is the actual path that was not found (e.g. '/etc/config.yaml')
	Path string
}

// Message creates a new i18n message using the template data.
func (td PathNotFoundTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "path-not-found.dynamic-error",
		Description: "Directory or file path does not exist",
		Other:       "{{.Name}} path not found ({{.Path}})",
	}
}

// PathNotFoundError Directory or file path does not exist.
type PathNotFoundError struct {
	li18ngo.LocalisableError
	PathNotFoundTemplData
}

// NewPathNotFoundError creates a new PathNotFoundError.
func NewPathNotFoundError(name string, path string) error {
	td := PathNotFoundTemplData{
		Li18ngoTemplData: Li18ngoTemplData{},
		Name:             name,
		Path:             path,
	}
	return &PathNotFoundError{
		LocalisableError:      li18ngo.LocalisableError{Data: td},
		PathNotFoundTemplData: td,
	}
}

// =============================================================================
// ❌ ThirdPartyWrapper
//
// ThirdPartyErrorWrapper is used to wrap errors from third-party libraries.
// =============================================================================

// ThirdPartyWrapperErrorTemplData Wrapper for third-party errors.
type ThirdPartyWrapperErrorTemplData struct {
	Li18ngoTemplData
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td ThirdPartyWrapperErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "third-party.error-wrapper-msg",
		Description: "Wrapper for third-party errors",
		Other:       "Third party error occurred: '{{.Wrapped}}'",
	}
}

// ThirdPartyWrapperError Wrapper for third-party errors.
type ThirdPartyWrapperError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e ThirdPartyWrapperError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e ThirdPartyWrapperError) Unwrap() error {
	return e.wrapped
}

// NewThirdPartyWrapperError creates a new ThirdPartyWrapperError wrapping
// wrapped.
func NewThirdPartyWrapperError(wrapped error) error {
	return &ThirdPartyWrapperError{
		LocalisableError: li18ngo.LocalisableError{
			Data: ThirdPartyWrapperErrorTemplData{Wrapped: wrapped.Error()},
		},
		wrapped: wrapped,
	}
}
